[workspace]
resolver = "2"

members = [
    "chrono_panic_poc",
    "clap_panic_poc",
    "httpie",
    "leetcode",
    "samples",
    "scrabble",
    "smart_pointers_poc",
    "sqlx_migration_poc",
]
