[package]
name = "samples"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html2md = "0.2.13"
reqwest = { version = "0.11.4", features = ["blocking"] }
