[package]
name = "ldap_client_poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["cargo"] }
ldap3 = "0.11.3"
tokio = { workspace = true }
